#!/bin/sh

APPID=com.nizovn.androidchroot
CSRVID=com.nizovn.androidchroot.main.c
CSRVID2=com.nizovn.androidchroot.shutdown.c
CSRVID3=com.nizovn.androidchroot.client.c

APPS=/media/cryptofs/apps

[ -d ${APPS} ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the C service executable
rm -f /var/usr/sbin/${CSRVID}
rm -f /var/usr/sbin/${CSRVID2}
rm -f /var/usr/sbin/${CSRVID3}

# Remove the dbus service
rm -f /var/palm/ls2/services/prv/${CSRVID}.service
rm -f /var/palm/ls2/services/pub/${CSRVID}.service
rm -f /var/palm/ls2/services/prv/${CSRVID2}.service
rm -f /var/palm/ls2/services/pub/${CSRVID2}.service
rm -f /var/palm/ls2/services/prv/${CSRVID3}.service
rm -f /var/palm/ls2/services/pub/${CSRVID3}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${CSRVID}.json /var/palm/ls2/roles/pub/${CSRVID}.json
rm -f /var/palm/ls2/roles/prv/${CSRVID2}.json /var/palm/ls2/roles/pub/${CSRVID2}.json
rm -f /var/palm/ls2/roles/prv/${CSRVID3}.json /var/palm/ls2/roles/pub/${CSRVID3}.json

# Stop the C service if running
/sbin/stop ${CSRVID} || true
/usr/bin/killall -9 ${CSRVID} || true
/sbin/stop ${CSRVID2} || true
/usr/bin/killall -9 ${CSRVID2} || true
/sbin/stop ${CSRVID3} || true
/usr/bin/killall -9 ${CSRVID3} || true

# Remove the upstart script
rm -f /var/palm/event.d/${CSRVID}
rm -f /var/palm/event.d/${CSRVID2}
rm -f /var/palm/event.d/${CSRVID3}

# Turn off Android
${APPS}/usr/palm/applications/${APPID}/scripts/kill.sh
${APPS}/usr/palm/applications/${APPID}/scripts/umount.sh

exit 0
